### PR TITLE
Support URL import for modern browser and Deno

### PR DESCRIPTION
**Pull request by kahirokunn**

### CODE REVIEW

**Comment by phryneas** [comment]
Hmm, haven't really played with either of those, but wouldn't those also still work as relative imports?

**Comment by phryneas** [comment]
Also, there's the chance that this would be generated for a `fetchBaseImport` that will be there in the future, but is not up yet. So maybe at that point we should just accept that it's an url import and they know what they're doing and not try to download the file? Not really sure :thinking:

**Comment by kahirokunn** [comment]
I'm sorry, I don't know much about this.
Are you talking about security concerns?  👀

**Comment by msutkowski** [comment]
> I'm sorry, I don't know much about this.
> Are you talking about security concerns? 👀

I think @phryneas is talking about this portion https://github.com/rtk-incubator/rtk-query-codegen/pull/31/files#diff-3397e7b2cc5a0db9dd95c724bdeb3cbc6567046c981c1caf27495242a4fe6f7fR55-R68 - instead of `throw`ing on the URL not loading or validating that it exists, we just leave the URL as entered, because the developer might _know for sure_ that it will be available in the future). It might be a good idea to just use `chalk` and warn in this case instead of `throw`ing.

**Comment by kahirokunn** [comment]
I see.
What if the path is a node_modules that you know will definitely be available in the future? :eyes:

Is it better to do `throw new Error(MESSAGES.FILE_NOT_FOUND)` only if the path is relative :eyes:

Or, how about making validation on/off switchable by cli option?

**Comment by kahirokunn** [comment]
@phryneas @msutkowski In the meantime, I've refactored it a bit and reflect your review. 👍

**Comment by msutkowski** [comment]
> @phryneas @msutkowski In the meantime, I've refactored it a bit and reflect your review. 👍

Looks great to me. I'll do another read through it later tonight or tomorrow unless @phryneas weighs in first. Thanks again @kahirokunn! 

From your last post, I think we should just add this in and it's about as flexible as it can be. 

> Or, how about making validation on/off switchable by cli option?

**Comment by phryneas** [comment]
Without having read the code right now (sorry, on the run), my main concern is that we are adding a lot of code to this project just to handle the case of an import statement.

All that needs to be maintained. I'd like to find a feasible balance there.

And downloading urls, parsing them, checking for correct exports... all that is nice. But the second the dev is going to integrate the generated file in their project and open it in an editor, they will get a TypeScript warning exactly telling them what went wrong anyways. So we are doing a *lot* of work just to handle non-everyday cases a minute earlier. 
If you compare this with graphql-codegen, they just insert arbitrary text snippets from the config and are rolling good with it.

If there are so many cases we would have to cover, I'd even go so far and say "let's just generate a second file for a baseQuery right next to it (which will never be overridden in the future) and have the dev just do their imports & changes to baseQuery manually there". Because that way we just covered every edge-case in existence with very little overhead on our side.

**Comment by kahirokunn** [comment]
Getting rid of validations and allowing simple code insertion is certainly a good idea!
Do I need to modify it that way?

**Comment by msutkowski** [comment]
We're going to pass on this for now, but thank you!

**Comment by phryneas** [comment]
To explain a second: Long-term plans are to just import an empty api and `inject` into that, so all of this would not be done on the command line any more, but you would just write your own code in your own file - which would make this obsolete

**Pull request closed without merging**
