### PR TITLE
fix: ts 4.5 compat

### PR DESCRIPTION
**Pull request by phryneas**

### CODE REVIEW

**Comment by Meligy** [comment]
I tried it locally as follows:

```zsh
# After cloning and switching to branch
npm i typescript -q && npm exec tsc -- --version && npm run build
```

But it fails because of another file:
```
src/generators/import-node.ts:16:21 
```

image

And I can see the failure in VS Code as well.

image

Looks like just another call site that needs to be updated similarly.

I searched for `createImportSpecifier` in the project and it seems the only remaining place calling it.

**Comment by Meligy** [comment]
I think it can be tested as follows:

```zsh
# git clone the repo and switch to PR branch

npm i typescript -q && npm exec tsc -- --version && npm run build

curl -o petstore.json https://petstore3.swagger.io/api/v3/openapi.json

node lib/bin/cli.js --hooks petstore.json > petstore-api.generated.ts

head -1 petstore-api.generated.ts
# or install dependencies and run `npm exec tsc petstore-api.generated.ts`
```

Or at least this is my plan for testing.

**Comment by Meligy** [comment]
It can be fixed by:

```patch
diff --git a/src/generators/import-node.ts b/src/generators/import-node.ts
index 2bc805741a6f7649f4bc965ec57a1068e4aa7b73..ce0bcb172ea6b7fc9f5c9fbcd411961a319638a4 100644
--- a/src/generators/import-node.ts
+++ b/src/generators/import-node.ts
@@ -1,4 +1,5 @@
 import * as ts from 'typescript';
+import { createImportSpecifier } from '../codegen';
 
 const { factory } = ts;
 
@@ -13,7 +14,7 @@ export function generateImportNode(pkg: string, namedImports: Record<string, str
         Object.entries(namedImports)
           .filter((args) => args[1])
           .map(([propertyName, name]) =>
-            factory.createImportSpecifier(
+            createImportSpecifier(
               name === propertyName ? undefined : factory.createIdentifier(propertyName),
               factory.createIdentifier(name as string)
             )
diff --git a/src/codegen.ts b/src/codegen.ts
index b4a1c567b9738dbf9d71fe3302a0e3072bb7e6c3..2959c41643d10fb1fa29b52357b5c174f0125a90 100644
--- a/src/codegen.ts
+++ b/src/codegen.ts
@@ -17,7 +17,7 @@ export function generateStringLiteralArray(arr: string[]) {
   );
 }
 
-function createImportSpecifier(propertyName: ts.Identifier | undefined, name: ts.Identifier): ts.ImportSpecifier {
+export function createImportSpecifier(propertyName: ts.Identifier | undefined, name: ts.Identifier): ts.ImportSpecifier {
   if (semver.satisfies(ts.version, '>= 4.5'))
     // @ts-ignore
     return factory.createImportSpecifier(false, propertyName, name);

```

And to test a proper test:

```zsh
git clean -dfx

npm i typescript -q && npm exec tsc -- --version && npm run build

curl -o petstore.json https://petstore3.swagger.io/api/v3/openapi.json

node lib/bin/cli.js --hooks petstore.json > petstore-api.generated.ts

# The result should be: `import { createApi } from "@reduxjs/toolkit/query/react";`
head -1 petstore-api.generated.ts

# required for typescript compilation to work
npm i -d react-redux

npm exec tsc petstore-api.generated.ts
```

**Comment by phryneas** [comment]
Thanks, I totally missed that one. Let me add that and then I'll push out a fix release.

**Comment by Meligy** [comment]
Thanks heaps.

**Pull request merged**
